"""add openai oauth fields to settings

Revision ID: 267dcee7b580
Revises: 016_user_style_templates
Create Date: 2026-04-25 16:17:37.742783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '267dcee7b580'
down_revision = '016_user_style_templates'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('settings', 'openai_oauth_access_token'):
        op.add_column('settings', sa.Column('openai_oauth_access_token', sa.Text(), nullable=True))
    if not _column_exists('settings', 'openai_oauth_refresh_token'):
        op.add_column('settings', sa.Column('openai_oauth_refresh_token', sa.Text(), nullable=True))
    if not _column_exists('settings', 'openai_oauth_expires_at'):
        op.add_column('settings', sa.Column('openai_oauth_expires_at', sa.DateTime(), nullable=True))
    if not _column_exists('settings', 'openai_oauth_account_id'):
        op.add_column('settings', sa.Column('openai_oauth_account_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _column_exists('settings', 'openai_oauth_account_id'):
        op.drop_column('settings', 'openai_oauth_account_id')
    if _column_exists('settings', 'openai_oauth_expires_at'):
        op.drop_column('settings', 'openai_oauth_expires_at')
    if _column_exists('settings', 'openai_oauth_refresh_token'):
        op.drop_column('settings', 'openai_oauth_refresh_token')
    if _column_exists('settings', 'openai_oauth_access_token'):
        op.drop_column('settings', 'openai_oauth_access_token')
    # ### end Alembic commands ###


