"""add openai_image_api_protocol to settings

Revision ID: 416cd372ad39
Revises: 819293cce08c
Create Date: 2026-04-27 02:39:29.870635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '416cd372ad39'
down_revision = '819293cce08c'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('settings', 'openai_image_api_protocol'):
        op.add_column('settings', sa.Column('openai_image_api_protocol', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _column_exists('settings', 'openai_image_api_protocol'):
        op.drop_column('settings', 'openai_image_api_protocol')
    # ### end Alembic commands ###


