"""add description_generation_mode to settings

Revision ID: 64ecc9f34de0
Revises: 88054bda1ece
Create Date: 2026-03-01 22:23:58.171031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ecc9f34de0'
down_revision = '88054bda1ece'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('description_generation_mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'description_generation_mode')
    # ### end Alembic commands ###



