"""add outline and description requirements to projects

Revision ID: 88054bda1ece
Revises: 015
Create Date: 2026-03-01 21:57:23.450061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '88054bda1ece'
down_revision = '015'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('projects', 'outline_requirements'):
        op.add_column('projects', sa.Column('outline_requirements', sa.Text(), nullable=True))
    if not _column_exists('projects', 'description_requirements'):
        op.add_column('projects', sa.Column('description_requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _column_exists('projects', 'description_requirements'):
        op.drop_column('projects', 'description_requirements')
    if _column_exists('projects', 'outline_requirements'):
        op.drop_column('projects', 'outline_requirements')
    # ### end Alembic commands ###


