"""add outline and description requirements to projects

Revision ID: 88054bda1ece
Revises: 015
Create Date: 2026-03-01 21:57:23.450061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88054bda1ece'
down_revision = '015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('outline_requirements', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('description_requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'description_requirements')
    op.drop_column('projects', 'outline_requirements')
    # ### end Alembic commands ###



