"""add description_extra_fields to settings

Revision ID: 9439faddcdd5
Revises: 64ecc9f34de0
Create Date: 2026-03-03 00:22:54.296186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9439faddcdd5'
down_revision = '64ecc9f34de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('description_extra_fields', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'description_extra_fields')
    # ### end Alembic commands ###



