"""add image_prompt_extra_fields to settings

Revision ID: 9ad736fec43d
Revises: 9439faddcdd5
Create Date: 2026-03-04 21:52:36.488053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '9ad736fec43d'
down_revision = '9439faddcdd5'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('settings', 'image_prompt_extra_fields'):
        op.add_column('settings', sa.Column('image_prompt_extra_fields', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _column_exists('settings', 'image_prompt_extra_fields'):
        op.drop_column('settings', 'image_prompt_extra_fields')
    # ### end Alembic commands ###


