"""add image_prompt_extra_fields to settings

Revision ID: 9ad736fec43d
Revises: 9439faddcdd5
Create Date: 2026-03-04 21:52:36.488053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad736fec43d'
down_revision = '9439faddcdd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('image_prompt_extra_fields', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'image_prompt_extra_fields')
    # ### end Alembic commands ###



