"""add caption and original_filename to materials

Revision ID: c153f8c4e111
Revises: 9ad736fec43d
Create Date: 2026-03-07 16:40:18.053611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'c153f8c4e111'
down_revision = '9ad736fec43d'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('materials', 'caption'):
        op.add_column('materials', sa.Column('caption', sa.String(length=500), nullable=True))
    if not _column_exists('materials', 'original_filename'):
        op.add_column('materials', sa.Column('original_filename', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _column_exists('materials', 'original_filename'):
        op.drop_column('materials', 'original_filename')
    if _column_exists('materials', 'caption'):
        op.drop_column('materials', 'caption')
    # ### end Alembic commands ###


